services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile.postgres
    image: udla_postgres
    container_name: udla_postgres
    restart: always
    env_file: .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --locale=C"
    ports:
      - "5440:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init_databases.sql:/docker-entrypoint-initdb.d/01_init_databases.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app-net
  
  authservice:
    image: dase123/udlaia-stats:authservice
    container_name: authservice
    env_file: .env
    environment:
      DEBUG: "true"
      ALLOWED_HOSTS: ${ALLOWED_HOSTS}
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: ${POSTGRES_DB_AUTH}
      FRONTEND_URL: ${FRONTEND_URL}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      DJANGO_SUPERUSER_PASSWORD: ${DJANGO_SUPERUSER_PASSWORD}
      DJANGO_SUPERUSER_USERNAME: ${DJANGO_SUPERUSER_USERNAME}
      DJANGO_SUPERUSER_EMAIL: ${DJANGO_SUPERUSER_EMAIL}
      API_PORT: ${API_PORT_AUTH}
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8010:8010"
    networks:
      - app-net
  
  teamservice:
    image: dase123/udlaia-stats:teamservice
    container_name: teamservice
    env_file: .env
    environment:
      DEBUG: "true"
      ALLOWED_HOSTS: ${ALLOWED_HOSTS}
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: ${POSTGRES_DB_TEAMS}
      FRONTEND_URL: ${FRONTEND_URL}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      SECRET_KEY: ${SECRET_KEY_TEAMS}
      API_PORT: ${API_PORT_TEAMS}
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8020:8020"
    networks:
      - app-net

  studentservice:
    image: dase123/udlaia-stats:studentservice
    container_name: studentservice
    env_file: .env
    environment:
      DEBUG: "true"
      ALLOWED_HOSTS: ${ALLOWED_HOSTS}
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: ${POSTGRES_DB_STUDENTS}
      FRONTEND_URL: ${FRONTEND_URL}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      SECRET_KEY: ${SECRET_KEY_STUDENTS}
      API_PORT: ${API_PORT_STUDENTS}
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8030:8030"
    networks:
      - app-net

name: udlaia-stats

volumes:
  postgres_data:
    driver: local

networks:
  app-net:
    driver: bridge